import { Listing, ListingStatus, AmenityStatus, Language } from './types';

export const SUBURBS = [
  "Diepkloof",
  "Orlando",
  "Tembisa",
  "Alexandra",
  "Khayelitsha",
  "Umlazi",
  "Mamelodi",
  "Soshanguve"
];

const ENGLISH_DEFAULTS = {
  stayWithUs: "Stay with us",
  tenantRole: "I'm a Tenant",
  tenantDesc: "Looking for a place to stay",
  landlordRole: "I'm a Landlord",
  landlordDesc: "I want to list a room",
  searchPlaceholder: "Search rooms, suburbs...",
  allLocations: "All Locations",
  price: "Price",
  rentPerMonth: "per month",
  deposit: "Deposit",
  safetyRating: "Safety Score",
  callNow: "Call Now",
  viewMap: "View on Map",
  report: "Report",
  back: "Back",
  listRoom: "List Your Room",
  postListing: "Post Listing",
  wifi: "WiFi",
  water: "Water",
  electricity: "Electricity",
  bathroom: "Bath",
  furnished: "Furnished",
  availableNow: "Available Now",
  taken: "Taken",
  availableFrom: "Available From",
  safeRenting: "Safe Renting: Never pay deposit before viewing the property.",
  switchRole: "Switch Role",
  results: "Results",
  noResults: "No rooms found matching your criteria.",
  clearFilters: "Clear Filters",
  listView: "List",
  mapView: "Map",
  landlordDetails: "Landlord Details",
  resName: "Residence Name",
  street: "Street Address",
  descPlaceholder: "Describe your room...",
  aiGenerate: "AI Generate",
  photos: "Photos",
  free: "Free",
  paid: "Paid",
  notAvailable: "N/A",
  newest: "Newest",
  priceLow: "Price: Low to High",
  priceHigh: "Price: High to Low",
  safety: "Safety",
  selectLanguage: "Select Language",
  welcome: "Welcome",
  enterPhone: "Enter Phone Number",
  sendOtp: "Send OTP",
  enterOtp: "Enter Verification Code",
  verify: "Verify",
  resend: "Resend Code",
  invalidOtp: "Invalid Code. Try 1234.",
  phonePlaceholder: "e.g. 071 234 5678"
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: ENGLISH_DEFAULTS,
  zu: {
    stayWithUs: "Hlala nathi",
    tenantRole: "Ngifuna Indawo",
    tenantDesc: "Ngidinga irenti",
    landlordRole: "Nginendawo",
    landlordDesc: "Ngifuna ukuqashisa",
    searchPlaceholder: "Sesha amagumbi...",
    allLocations: "Izindawo Zonke",
    price: "Inani",
    rentPerMonth: "ngenyanga",
    deposit: "Idiphozi",
    safetyRating: "Ukuphepha",
    callNow: "Shaya Ucingo",
    viewMap: "Buka eMbalazweni",
    report: "Bika",
    back: "Emuva",
    listRoom: "Faka Indawo Yakho",
    postListing: "Shicilela",
    wifi: "I-WiFi",
    water: "Amanzi",
    electricity: "Ugesi",
    bathroom: "Indlu yangasese",
    furnished: "Ifenisha ikhona",
    availableNow: "Iyakholakala",
    taken: "Isithathiwe",
    availableFrom: "Iyakholakala kusukela",
    safeRenting: "Qaphela: Ungakhokhi imali ungayibonanga indawo.",
    switchRole: "Shintsha",
    results: "Imiphumela",
    noResults: "Ayikho imiphumela.",
    clearFilters: "Susa okuhlungayo",
    listView: "Uhlu",
    mapView: "Imephu",
    landlordDetails: "Imininingwane Yomnikazi",
    resName: "Igama Lendawo",
    street: "Ikheli",
    descPlaceholder: "Chaza indawo yakho...",
    aiGenerate: "Bhala nge-AI",
    photos: "Izithombe",
    free: "Mahhala",
    paid: "Kuyakhokhelwa",
    notAvailable: "Ayikho",
    newest: "Okusha kuqala",
    priceLow: "Inani: Phansi kuye Phezulu",
    priceHigh: "Inani: Phezulu kuye Phansi",
    safety: "Ukuphepha",
    selectLanguage: "Khetha Ulimi",
    welcome: "Siyakwamukela",
    enterPhone: "Faka Inombolo Yocingo",
    sendOtp: "Thumela i-OTP",
    enterOtp: "Faka Ikhodi",
    verify: "Qinisekisa",
    resend: "Thumela futhi",
    invalidOtp: "Ikhodi ayilungile. Zama 1234.",
    phonePlaceholder: "Isib. 071 234 5678"
  },
  xh: {
    stayWithUs: "Hlala nathi",
    tenantRole: "Ndingumqeshi",
    tenantDesc: "Ndikhangela indawo",
    landlordRole: "Ndinendawo",
    landlordDesc: "Ndifuna ukuqeshisa",
    searchPlaceholder: "Khangela amagumbi...",
    allLocations: "Zonke iindawo",
    price: "Ixabiso",
    rentPerMonth: "ngenyanga",
    deposit: "Idipozithi",
    safetyRating: "Ukhuseleko",
    callNow: "Tsalela Umnxeba",
    viewMap: "Jonga eMapini",
    report: "Xela",
    back: "Umva",
    listRoom: "Dwelisa Igumbi",
    postListing: "Papashela",
    wifi: "I-WiFi",
    water: "Amanzi",
    electricity: "Umbane",
    bathroom: "Igumbi lokuhlambela",
    furnished: "Ifenitshalaikhona",
    availableNow: "Iyafumaneka",
    taken: "Ithathiwe",
    availableFrom: "Iyafumaneka ukusuka",
    safeRenting: "Ukhuseleko: Ungahlawuli ungayibonanga indawo.",
    switchRole: "Tshintsha",
    results: "Iziphumo",
    noResults: "Akukho ziphumo.",
    clearFilters: "Cima izihluzi",
    listView: "Uluhlu",
    mapView: "Imapu",
    landlordDetails: "Iinkcukacha zomnini",
    resName: "Igama Lendawo",
    street: "Idilesi Yesitrato",
    descPlaceholder: "Chaza igumbi lakho...",
    aiGenerate: "Bhala nge-AI",
    photos: "Iifoto",
    free: "Simahla",
    paid: "Iyahlawulelwa",
    notAvailable: "Ayifumaneki",
    newest: "Entsha kuqala",
    priceLow: "Ixabiso: Ezantsi ukuya Phezulu",
    priceHigh: "Ixabiso: Phezulu ukuya Ezantsi",
    safety: "Ukhuseleko",
    selectLanguage: "Khetha Ulwimi",
    welcome: "Wamkelekile",
    enterPhone: "Faka Inombolo Yefowuni",
    sendOtp: "Thumela i-OTP",
    enterOtp: "Faka iKhowudi",
    verify: "Qinisekisa",
    resend: "Thumela kwakhona",
    invalidOtp: "Ikhodi ayilunganga. Zama 1234.",
    phonePlaceholder: "Umz. 071 234 5678"
  },
  // Placeholder translations for other South African languages (defaulting to English for functionality)
  nso: { ...ENGLISH_DEFAULTS, selectLanguage: "Kgetha Leleme" }, // Sepedi
  st: { ...ENGLISH_DEFAULTS, selectLanguage: "Khetha Puo" }, // Sesotho
  tn: { ...ENGLISH_DEFAULTS, selectLanguage: "Tlhopha Puo" }, // Setswana
  ts: { ...ENGLISH_DEFAULTS, selectLanguage: "Hlawula Ririmi" }, // Xitsonga
  ss: { ...ENGLISH_DEFAULTS, selectLanguage: "Khetsa Lulwimi" }, // siSwati
  ve: { ...ENGLISH_DEFAULTS, selectLanguage: "Khethani Luambo" }, // Tshivenda
  nr: { ...ENGLISH_DEFAULTS, selectLanguage: "Khetha Ilimi" }, // isiNdebele
};

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'MaDlamini’s Place',
    address: {
      street: '123 Vilakazi St',
      suburb: 'Diepkloof',
      city: 'Soweto',
      province: 'Gauteng',
      lat: -26.2527,
      lng: 27.9546
    },
    price: 2500,
    deposit: 1000,
    description: 'Neat and secure backroom with tiles and ceiling. Very safe yard with locked gates.',
    safety: 85,
    rating: 4.8,
    landlordId: 'user1',
    landlordName: 'Gogo Dlamini',
    contactPhone: '071 555 1234',
    contactWhatsApp: true,
    landlordIdNumber: '5001010000080',
    status: ListingStatus.AVAILABLE,
    photos: [
      'https://images.unsplash.com/photo-1526308593555-539923361e60?auto=format&fit=crop&w=800&q=60', // Interior
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60',  // Exterior
    ],
    amenities: {
      wifi: AmenityStatus.FREE,
      water: AmenityStatus.FREE,
      electricity: AmenityStatus.PAID,
      bathroom: AmenityStatus.FREE,
    },
    beds: 1,
    baths: 1,
    furnished: true,
    createdAt: Date.now(),
  },
  {
    id: '2',
    title: 'Kasi Living Units',
    address: {
      street: '45 Freedom Drive',
      suburb: 'Tembisa',
      city: 'Johannesburg',
      province: 'Gauteng',
      lat: -25.9964,
      lng: 28.2268
    },
    price: 1800,
    deposit: 1800,
    description: 'Affordable room, close to taxi rank. Shared shower.',
    safety: 65,
    rating: 3.5,
    landlordId: 'user2',
    landlordName: 'Mr. Khumalo',
    contactPhone: '083 555 9876',
    contactWhatsApp: false,
    landlordIdNumber: '8001010000080',
    status: ListingStatus.TAKEN,
    photos: [
      'https://images.unsplash.com/photo-1505693416388-b0346efee535?auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=800&q=60',
    ],
    amenities: {
      wifi: AmenityStatus.NOT_AVAILABLE,
      water: AmenityStatus.FREE,
      electricity: AmenityStatus.PAID,
      bathroom: AmenityStatus.FREE,
    },
    beds: 0,
    baths: 1,
    furnished: false,
    createdAt: Date.now() - 100000,
  },
  {
    id: '3',
    title: 'Sunset Cottages',
    address: {
      street: '88 Mandela Ave',
      suburb: 'Khayelitsha',
      city: 'Cape Town',
      province: 'Western Cape',
      lat: -34.0363,
      lng: 18.6730
    },
    price: 3200,
    deposit: 1500,
    description: 'Modern cottage with aluminum windows. Parking available.',
    safety: 78,
    rating: 4.2,
    landlordId: 'user3',
    landlordName: 'Sipho',
    contactPhone: '062 000 1111',
    contactWhatsApp: true,
    landlordIdNumber: '9001010000080',
    status: ListingStatus.AVAILABLE_FROM,
    availableDate: '2023-11-01',
    photos: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=60',
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=800&q=60',
    ],
    amenities: {
      wifi: AmenityStatus.PAID,
      water: AmenityStatus.FREE,
      electricity: AmenityStatus.FREE,
      bathroom: AmenityStatus.FREE,
    },
    beds: 1,
    baths: 1,
    furnished: false,
    createdAt: Date.now() - 500000,
  }
];